### ISSUE TITLE
ERROR: SQLSTATE[22S03]: <>: 3617 Latitude 122.232690 is out of range in function st_pointfromtext.

### ISSUE THREAD

**Issue by mojxznhek** [eusonlito/GPS-Tracker#12]
> [2023-04-26 09:01:41] production.ERROR: SQLSTATE[22S03]: <<Unknown error>>: 3617 Latitude 122.232690 is out of range in function st_pointfromtext. It must be within [-90.000000, 90.000000]. (Connection: mysql, SQL: insert into `position` (`point`, `speed`, `direction`, `signal`, `date_at`, `date_utc_at`, `device_id`, `timezone_id`, `trip_id`, `user_id`, `vehicle_id`) values (ST_PointFromText("POINT(122.232690 10.647180)", 4326), 0, 0, 1, 2023-04-26 17:01:38, 2023-04-26 09:01:38, 1, 259, 1, 1, 1)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 22S03): SQLSTATE[22S03]: <<Unknown error>>: 3617 Latitude 122.232690 is out of range in function st_pointfromtext. It must be within [-90.000000, 90.000000]. (Connection: mysql, SQL: insert into `position` (`point`, `speed`, `direction`, `signal`, `date_at`, `date_utc_at`, `device_id`, `timezone_id`, `trip_id`, `user_id`, `vehicle_id`) values (ST_PointFromText(\"POINT(122.232690 10.647180)\", 4326), 0, 0, 1, 2023-04-26 17:01:38, 2023-04-26 09:01:38, 1, 259, 1, 1, 1)) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:793)

**Comment by eusonlito** [comment]
What GPT tracking device are you using?

**Comment by eusonlito** [comment]
I think is related with MySQL version: https://dba.stackexchange.com/a/242004/23729

Anyway I have sent a patch to force always same parameters order: https://dba.stackexchange.com/a/313905/23729

**Comment by mojxznhek** [comment]
Im using ST-901M Sinotrack GPS Tracker
![image](https://user-images.githubusercontent.com/38281053/234805491-6d0a4860-cec2-4705-b0c4-1388d6c6335f.png)

**Comment by eusonlito** [comment]
Ok, update the code and test it again :)

**Comment by mojxznhek** [comment]
Hi, here's the update. Data are now saving. here's another issue. see the image attached.
![image](https://user-images.githubusercontent.com/38281053/234810788-fb2eddbb-478b-476d-8414-68a04bb1505b.png)
coordinates are not working on map.
![image](https://user-images.githubusercontent.com/38281053/234810877-4dfee850-614a-403c-9056-571ecbb576de.png)

**Comment by mojxznhek** [comment]
I think it should be Lat-Long order. 

![image](https://user-images.githubusercontent.com/38281053/234811897-39dd8f6a-e291-4ede-b237-80807dba22ce.png)

**Comment by eusonlito** [comment]
Can you send me the socket log stored in `Server > Logs` > `server / 2023-04-27 / 8091.log`

Please, send the trace to lito at eordes.com to avoid expose your device IDs.

**Comment by mojxznhek** [comment]
I just sent the 8091.log on your email.
Thanks

**Comment by eusonlito** [comment]
I have found the error, but to be fixed the trips must be deleted because coordinates range.

You can import the trips again from logs using the command:

```
php artisan server:log:read --file storage/logs/server/2023-04-XX/8091.log --protocol h02
```

It's ok?

**Comment by mojxznhek** [comment]
Hi, here's the update. it's now working. 
![image](https://user-images.githubusercontent.com/38281053/235019966-f9779281-546f-4163-ac57-a6039692c536.png)

I think this is now resolved. thanks a lot.

**Comment by eusonlito** [comment]
Thank you very much for your collaboration!

Closing :)
