### ISSUE TITLE
error run local 

### ISSUE THREAD

**Issue by autotrafego** [eusonlito/GPS-Tracker#14]
I ran local, but the dashboard gives error 500, the ports the restart command gives error:
![Captura de tela 2023-05-31 231356](https://github.com/eusonlito/GPS-Tracker/assets/16263632/87379898-f13a-432e-8fae-af36d351b6d9)

**Comment by eusonlito** [comment]
The restart command is:

```
php artisan server:start:all --reset
```

You should check the PHP/Apache/Laravel log to discover the error 500.
