### ISSUE TITLE
Puede funcionar sin REDIS

### ISSUE THREAD

**Issue by alnux** [eusonlito/GPS-Tracker#15]
tengo un host en internet pero no tiene redis, el software puede funcionar sin redis. y tambien me preguntaba como podria un cliente de traccar (android apk) enviar las coordenadas al software

**Comment by eusonlito** [comment]
Hola, no puede funcionar sin redis ya que se usa para algunos procesos que se ejecutan en background mediante colas. La APP de traccar es sólo compatible con el API propio de traccar, no es intercambiable. Igual puedes instalar la aplicación de OsmAnd y crear un servidor OsmAnd en el GPS Tracker que reciba las posiciones https://osmand.net/docs/user/plugins/osmand-tracker/

**Comment by alnux** [comment]
@eusonlito acabo de instalar la aplicación (osmand-tracker) que me recomendaste pero solo me pregunta por contactos o grupos a quienes compartir mi ubicación y no encuentro por ningún lado como configurar el envío de datos a mi servidor. Cómo puedo hacer esto???

**Comment by eusonlito** [comment]
Vale, he estado revisando esa aplicación y sólo funciona contra su propio servidor. Lo ideal sería una aplicación que pueda enviar la geolocalización en formato OsmAnd donde puedas configurar el servidor remoto que recibe las peticiones, pero no he encontrado más.

**Comment by alnux** [comment]
@eusonlito en el deploy informa que se esta usando un paquete abandonado

`Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.`

**Comment by eusonlito** [comment]
Cerramos :)
