### ISSUE TITLE
Issue with seeding the database

### ISSUE THREAD

**Issue by paulmercs** [eusonlito/GPS-Tracker#25]
In Container.php line 914:
                                                 
  Target class [DatabaseSeeder] does not exist.  
                                                 

In Container.php line 912:
                                         
  Class "DatabaseSeeder" does not exist  
                                         
 When I seed the database this occurs

**Comment by eusonlito** [comment]
Hi! sorry my delay. Are you using Windows?

**Comment by eusonlito** [comment]
Sorry, windows is not supported by the requirements to be able to run the protocol servers.
