### ISSUE TITLE
Telegram Alert

### ISSUE THREAD

**Issue by d0bro** [eusonlito/GPS-Tracker#26]
Notifications do not work in TG Is there an example of what needs to be specified in these parameters?

TELEGRAM_BOT=
TELEGRAM_TOKEN=

**Comment by eusonlito** [comment]
You need to create your own Telegram Bot. You can do it using BotFather contact in Telegram, it will provide you the token.

**Comment by d0bro** [comment]
I've done it and I know how. I'm interested in the format in which to enter, because I enter this way
TELEGRAM_BOT=6888888883
TELEGRAM_TOKEN=AAE3rGr..................0i9EtGVPAgc
 or that way 
TELEGRAM_BOT=6888888883
TELEGRAM_TOKEN=6888888883:AAE3rGr..................0i9EtGVPAgc
or that way
TELEGRAM_BOT=299999998 (chat id)
TELEGRAM_TOKEN=6888888883:AAE3rGr..................0i9EtGVPAgc
and it doesn't work.

**Comment by eusonlito** [comment]
TELEGRAM_BOT is the Bot Name, for example + `d0bro_GPS_Bot`, and TELEGRAM_TOKEN is the full token `6888888883:AAE3rGr..................0i9EtGVPAgc`.

**Comment by eusonlito** [comment]
@d0bro solved? Can we close the issue?

**Comment by d0bro** [comment]
after changing .env, do I need to do something to make it work?

**Comment by eusonlito** [comment]
You need to regenerate config cache `php artisan optimize` and then connect to Bot in your profile `/profile/telegram`
