### ISSUE TITLE
Cannot change language

### ISSUE THREAD

**Issue by abosaad11** [eusonlito/GPS-Tracker#29]
Hello

I spent a few hours trying to change the language to English without any luck, this is for a docker container.

I have a `.env` file in the root directory and in the `/docker` directory just to be sure. Both look like this:

```
APP_NAME="GPS Tracker"
APP_ENV=production
APP_KEY=
APP_DEBUG=false

# Configure this if you are using a web server as proxy
APP_URL=http://localhost:8092

# Configure the default language (es/en)
APP_LOCALE=en
...
```

I even made the following changes to `/config/app.php`:

```
'locale' => 'en',
'fallback_locale' => 'en',
...
```
I followed the [README ](https://github.com/eusonlito/GPS-Tracker/blob/master/README.md) to the letter, but the container works in Spanish every single time. It won't change to English.

Please help, how am I supposed to change the language? Thank you

EDIT:

By complete accident I found `http://192.168.1.10:8092/profile` and I can change the language from there. Can I have the container boot into English by default?

**Comment by eusonlito** [comment]
Ok, spainsh is default system language, I need to update this setting to match with the default `APP_LOCALE`.

https://github.com/eusonlito/GPS-Tracker/blob/master/app/Domains/Language/Seeder/data/language.json

**Comment by abosaad11** [comment]
> Ok, spainsh is default system language, I need to update this setting to match with the default `APP_LOCALE`.
> 
> https://github.com/eusonlito/GPS-Tracker/blob/master/app/Domains/Language/Seeder/data/language.json

Thank you.

**Comment by eusonlito** [comment]
For now, you can change the default language from database:

```sql
UPDATE `language` SET `default` = FALSE;
UPDATE `language` SET `default` = TRUE WHERE `code` = "en";
```

**Comment by eusonlito** [comment]
Solved from commit https://github.com/eusonlito/GPS-Tracker/commit/1f9fa0278906b5cec676e7a1ccd54f2695161d02

Now the default language is checked from `.env` instead the `default` column.
