### ISSUE TITLE
does it support coban devices?

### ISSUE THREAD

**Issue by sajjadintel** [eusonlito/GPS-Tracker#32]
Hi,
does it support coban devices?

**Comment by eusonlito** [comment]
Currently not, but it seems to be easy to implement.

Adding this issue as feature.

**Comment by sajjadintel** [comment]
@eusonlito If you could explain I might be able to help out.

**Comment by eusonlito** [comment]
There are several steps to follow to add a new protocol, but basically it is to create a copy of H02 (Sinotrack) and adapt it for GP103 (Cobian).

**Comment by sajjadintel** [comment]
@eusonlito  I also need the feature to enable and disable Coban device.
Also being able to connect and disconnect car electricity using relay.
Could you add these or give me some instruction on how to do this?
Thanks.

**Comment by sajjadintel** [comment]
@eusonlito  Thanks for your response.
By messages do you mean SMS?
Do you have time to implement GP103 protocol in the near future?

**Comment by eusonlito** [comment]
No, direct messages from the platform to the device. It only works if the device is connected to the platform (not sleeping), but it is the alternative to SMS. I will try to start development next week, but I don't have a cobian device to test it.

**Comment by sajjadintel** [comment]
Thanks. I have the device I could help you with the testing.

**Comment by eusonlito** [comment]
@sajjadintel, I already have a first version available for testing. You could send me an email to lito@eordes.com and I will send you the connection instructions.

**Comment by eusonlito** [comment]
@sajjadintel you have a mail :)

**Comment by eusonlito** [comment]
[coban GPRS protocol.pdf](https://github.com/eusonlito/GPS-Tracker/files/13746683/coban.GPRS.protocol.pdf)

**Comment by eusonlito** [comment]
[GPRS data protocol.xls](https://github.com/eusonlito/GPS-Tracker/files/13757190/GPRS.data.protocol.xls)

**Comment by eusonlito** [comment]
@sajjadintel I have been checking messages send to the device and I have seen that the device receives the command, applies the changes, but responds nothing.... So I'm not clear if the functionality is like that or something configurable on the device.

Also I have checked the forum and issues of traccar and the same thing happens, so little else can be done.

**Comment by sajjadintel** [comment]
Should the device be on TCP or UDP mode? (attached a picture)

I sent disarm command via SMS: Disarm123456.
Also sent via gprs: **,imei:868166054696190,112
When I sent the command via SMS, device make a sound for enabling the siren. but this doesn't happen via GPRS.
means GPRS commands doesn't reach the device

**Comment by eusonlito** [comment]
Device should connect using TCP.

The available commands are in document [GPRS data protocol.xls](https://github.com/eusonlito/GPS-Tracker/files/13757190/GPRS.data.protocol.xls)

The comments in [coban GPRS protocol.pdf](https://github.com/eusonlito/GPS-Tracker/files/13746683/coban.GPRS.protocol.pdf) seems not working

**Comment by eusonlito** [comment]
Can this issue be closed?

**Comment by sajjadintel** [comment]
Yes, Thanks.
