### ISSUE TITLE
Support JimiLab JM-LL01

### ISSUE THREAD

**Issue by gaskoo1** [eusonlito/GPS-Tracker#33]
Maybe in near future did you support this device?

https://www.jimilab.com/products/jm-ll01-asset-gnss-tracker.html

https://flespi.com/devices/jimi-iot-concox-jm-ll01

**Comment by eusonlito** [comment]
Protocol is Concox, let me see.

**Comment by gaskoo1** [comment]
[LL01 Command List_V1.3_20210322.xlsx](https://github.com/eusonlito/GPS-Tracker/files/13784933/LL01.Command.List_V1.3_20210322.xlsx)

[Communication Protocol(JM-LL01,JM-LL02,CT10) V2.1.4 20200611.pdf](https://github.com/eusonlito/GPS-Tracker/files/13784934/Communication.Protocol.JM-LL01.JM-LL02.CT10.V2.1.4.20200611.pdf)

**Comment by eusonlito** [comment]
@gaskoo1 thanks! The protocol name is GT06.

**Comment by gaskoo1** [comment]
So what do you think? Can you implement this in the near future? If you could I would appreciate it.

**Comment by eusonlito** [comment]
Yes, I will try to get as soon as possible. I am now looking for a protocol communication log for testing.

**Comment by gaskoo1** [comment]
I can connect device to your server. Just send me IP and port

**Comment by eusonlito** [comment]
Send me an email to lito@eordes.com and I will get back to you with the server data.

**Comment by gaskoo1** [comment]
I send you mail

**Comment by eusonlito** [comment]
Can this issue be closed?

**Comment by sajjadintel** [comment]
Yes. Thanks.
