### ISSUE TITLE
response for coban devices

### ISSUE THREAD

**Issue by sajjadintel** [eusonlito/GPS-Tracker#37]
Hi,
When I send this to the device:
`**,imei:868166054696190,111`
device will send this response: (it will be shown in the server log file.)
`imei:868166054696190,111,240112185257,,F,152257.000,A,3531.37056,N,04610.27195,E,,,,0,0,0.00%,,;`
But it doesn't show in response for the request.
Thanks.

**Comment by eusonlito** [comment]
I have the log:

```
[2024-01-12 15:19:01.996 +00:00] [INFO] [65a1334972be2] [WRITE] **,imei:868166056076334,111
[2024-01-12 15:19:03.714 +00:00] [INFO] [65a1334972be2] [READ] imei:868166056076334,511,240112151902,,F,151902.000,A,3528.51503,N,04611.84315,E,,,,0,1,0.00%,,;
```

Write is from server to device and read is from device to server.

I wil check it.

**Comment by sajjadintel** [comment]
for enabling arm will return 111 but if car is turned on and it won't enable and will return 511

**Comment by eusonlito** [comment]
Added message response check for Coban devices.

**Comment by sajjadintel** [comment]
Hi, Yeah I've tested it and works. Thanks!
