### ISSUE TITLE
Theme issue: can't read texts

### ISSUE THREAD

**Issue by sajjadintel** [eusonlito/GPS-Tracker#39]
Hi,
Thank you for your hard work.
I'm facing a problem with panel theme. I can't read texts. could you change text colors to white?
Thanks.
![2024-01-18 21 28 51](https://github.com/eusonlito/GPS-Tracker/assets/13988374/d40537d4-f09f-4bb6-aa86-ef9ed8e97094)

**Comment by eusonlito** [comment]
Oh, it's strange, I can reproduce the error.

Do you have same problem from computer or another mobile browser?

![Screenshot_2024-01-18-23-14-24-37_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/eusonlito/GPS-Tracker/assets/644551/50f414f3-a23c-4f29-9621-83d735a078ae)

**Comment by sajjadintel** [comment]
Yeah, I think if the device theme is set to "Dark mode" this problem happens.
<img width="1186" alt="Screenshot 2024-01-19 at 01 49 20" src="https://github.com/eusonlito/GPS-Tracker/assets/13988374/058f9b21-1283-4f6a-b4c3-4e5e168a82fc">

**Comment by eusonlito** [comment]
Yes! It's dark mode. I don't know this!

I'm going to check how to fix it.

Thanks!

![Screenshot_2024-01-18-23-32-10-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/eusonlito/GPS-Tracker/assets/644551/06afb186-2383-4008-a8c5-96a278c97dc3)

**Comment by eusonlito** [comment]
Fixed!
