### ISSUE TITLE
Support Teltonika FMC003 

### ISSUE THREAD

**Issue by aamiel1** [eusonlito/GPS-Tracker#49]
Hi,

I Use Teltonika FMC003 Device but it not work, I get this warning:

deprecations-daily.WARNING: ErrorException: Invalid characters passed for attempted conversion, these have been ignored in /app/app/Services/Protocol/Teltonika/Parser/Locations.php:38

Stack trace:
#0 /app/vendor/laravel/framework/src/Illuminate/Support/helpers.php(470): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(Object(Illuminate\Log\Logger))
#1 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(103): with(Object(Illuminate\Log\Logger), Object(Closure))
#2 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(72): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError('Invalid charact...', '/app/app/Servic...', 38, 8192)
#3 /app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Invalid charact...', '/app/app/Servic...', 38)
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}(8192, 'Invalid charact...', '/app/app/Servic...', 38)
#5 /app/app/Services/Protocol/Teltonika/Parser/Locations.php(38): hexdec('\x0F9999360')
#6 /app/app/Services/Protocol/Teltonika/Parser/Locations.php(29): App\Services\Protocol\Teltonika\Parser\Locations->bodyIsValidStart()
#7 /app/app/Services/Protocol/Teltonika/Parser/Locations.php(15): App\Services\Protocol\Teltonika\Parser\Locations->bodyIsValid()
#8 /app/app/Services/Protocol/ProtocolAbstract.php(50): App\Services\Protocol\Teltonika\Parser\Locations->resources()
#9 /app/app/Domains/Server/Action/StartPort.php(159): App\Services\Protocol\ProtocolAbstract->resources('\x0F99993606361274...', Array)
#10 /app/app/Services/Server/Socket/Client.php(121): App\Domains\Server\Action\StartPort->store('\x0F99993606361274...', Array)
#11 /app/app/Services/Server/Socket/Client.php(62): App\Services\Server\Socket\Client->readHandle('\x0F99993606361274...')
#12 /app/app/Services/Server/Socket/Server.php(237): App\Services\Server\Socket\Client->handle()
#13 /app/app/Services/Server/Socket/Server.php(223): App\Services\Server\Socket\Server->connectionReadHandle(Object(App\Services\Server\Connection), Object(Closure))
#14 /app/app/Services/Server/Socket/Server.php(158): App\Services\Server\Socket\Server->connectionRead(Object(App\Services\Server\Connection), Object(Closure))
#15 /app/app/Services/Server/Socket/Server.php(85): App\Services\Server\Socket\Server->read(Object(Closure))
#16 /app/app/Domains/Server/Action/StartPort.php(146): App\Services\Server\Socket\Server->accept(Object(Closure))
#17 /app/app/Domains/Server/Action/StartPort.php(48): App\Domains\Server\Action\StartPort->serve()
#18 /app/app/Domains/Core/Action/ActionFactoryAbstract.php(55): App\Domains\Server\Action\StartPort->handle()
#19 /app/app/Domains/Server/Action/ActionFactory.php(60): App\Domains\Core\Action\ActionFactoryAbstract->actionHandle('App\\Domains\\Ser...', Array)
#20 /app/app/Domains/Server/Command/StartPort.php(29): App\Domains\Server\Action\ActionFactory->startPort()
#21 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Domains\Server\Command\StartPort->handle()
#22 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#23 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#24 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#25 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#26 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(212): Illuminate\Container\Container->call(Array)
#27 /app/vendor/symfony/console/Command/Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#28 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(181): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#29 /app/vendor/symfony/console/Application.php(1049): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /app/vendor/symfony/console/Application.php(318): Symfony\Component\Console\Application->doRunCommand(Object(App\Domains\Server\Command\StartPort), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /app/vendor/symfony/console/Application.php(169): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(196): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /app/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 {main}

**Comment by eusonlito** [comment]
The Teltonika protocol is still under development as I do not have any device for testing.

Would you be interested to connect your device with my platform in order to finalize the development?

If so, you can write me at lito [at] eordes [dot] com and I will send you the connection credentials.

Thanks!

**Comment by aamiel1** [comment]
No problem. I will send you an email.
Also you can learn how to do it from the traccar system.

Thanks
