### ISSUE TITLE
Fix Timezone

### ISSUE THREAD

**Issue by eusonlito** [eusonlito/GPS-Tracker#5]

**Comment by JakeOcean** [comment]
I was able to finally get my st-902 pointed at my own server. I think I was out of service when I attempted it before -- can these settings be changed with a USB cable?

I am seeing data in my logs.  I switched from debug-socket back to h02 -- the messages format is the same

```
[2023-02-25T18:26:45+00:00] *HQ,7018462432,V1,182552,A,4437.7528,N,08605.7779,W,000.00,292,250223,FBFFFBFF,000,00,0,0#
[2023-02-25T18:28:09+00:00] *HQ,7018462432,V1,182743,A,4438.0377,N,08605.4029,W,004.04,073,250223,FFFFFBFF,310,00,20502,185608458#
[2023-02-25T18:29:33+00:00] *HQ,7018462432,V1,182753,A,4438.0379,N,08605.4017,W,000.00,073,250223,FBFFFBFF,310,00,20502,185608458#
[2023-02-25T18:30:58+00:00] *HQ,7018462432,V1,183004,A,4438.5971,N,08605.1690,W,022.42,320,250223,FFFFFBFF,310,00,20502,185801238#
[2023-02-25T18:32:22+00:00] *HQ,7018462432,V1,183007,A,4438.6092,N,08605.1897,W,024.20,300,250223,FFFFFBFF,310,00,20502,185801238#
[2023-02-25T18:33:46+00:00] *HQ,7018462432,V1,183258,A,4439.2341,N,08606.5630,W,024.35,306,250223,FFFFFBFF,310,00,20502,185696520#
[2023-02-25T18:35:11+00:00] *HQ,7018462432,V1,183503,A,4439.5969,N,08607.4481,W,014.49,100,250223,FBFFFBFF,310,00,20502,185801238#
[2023-02-25T18:36:35+00:00] *HQ,7018462432,V1,183516,A,4439.5708,N,08607.3487,W,024.06,126,250223,FFFFFBFF,310,00,20502,185801238#
[2023-02-25T18:38:00+00:00] *HQ,7018462432,V1,183755,A,4439.4078,N,08606.9255,W,005.86,027,250223,FFFFFBFF,310,00,20502,185801238#
```
This data is not visible in the backend, so either the protocol is different, my settings are wrong, or perhaps I do not have the tracker ID entered correctly?

**Comment by JakeOcean** [comment]
On the backend my Device serial number is correctly set to `7018462432`

**Comment by eusonlito** [comment]
Ok, the data is correct to protocol H02. Let me check if there are some additional column or value not parsed by default regular expression 👍🏿

**Comment by JakeOcean** [comment]
After parking my car, several hours later a few trips appeared!  

The times are wrong, so I think I need to still set my device to use UTC perhaps?

Either way I think the protocol is working, based on the data, but I will let you know tomororw after I test a bit more.

<img width="898" alt="Screen Shot 2023-02-25 at 8 16 35 PM" src="https://user-images.githubusercontent.com/22035949/221387080-37294f36-436a-4e18-a84c-dd5698c2d3c0.png">

**Comment by JakeOcean** [comment]
Actually, those times are too late to be UTC... It's not 9:55 UTC on 2/26 yet..

**Comment by eusonlito** [comment]
Yes, you need to setup your device with UTC timezone: https://github.com/eusonlito/GPS-Tracker#set-the-time-zone-to-utc-to-delegate-the-time-adjustment-to-the-platform

**Comment by eusonlito** [comment]
Also you can send a message (same text as SMS) from `Devices` > `Messages`. But TCP messages need wait to device wake up to apply the change.

**Comment by JakeOcean** [comment]
I was able to update my Tracker to UTC -- thank you so much for your help!  

I have my Vehicle set to my local timezone of America/New_York and I just started a new drive -- the time seems to be off by 1 hour, so maybe it is a Daylight savings issue?  Either way, not a big deal for now.

I will drive around for a few days and test everything out, and then maybe I can contribute a few updates too if you are open to it

**Comment by eusonlito** [comment]
Can you check the server logs if device is reporting the correct UTC time?

```
[UTC_DATETIME] *HQ,DEVICE_ID,V1,UTC_TIME,...
```

Or in database tables `trip` and `position`, the columns `xxxxx_utc_at`.

Anyway I will do some tests with your same Timezone because I have found other users with a similae issue: https://stackoverflow.com/questions/74588944/getting-the-difference-in-time1-hour-for-daylight-saving-time-timezones-like-a

**Comment by JakeOcean** [comment]
When I check the DB, the UTC time is correct.

I started my trip at 11am est today, which is 4pm UTC.  Does your timezone selector take into account daylight savings time?  In the Spring and Fall we adjust our clocks 1 hour, which can be a pain in PHP, but thankfully Carbon usually handles it

![Screen Shot 2023-02-27 at 2 37 34 PM](https://user-images.githubusercontent.com/22035949/221665876-131ef7d2-d450-422a-9c62-763e07e63a1b.png)

**Comment by eusonlito** [comment]
Do you have enabled automatic timezone in vehicle? Can you show the rows columns in your screenshot?

In my case, with Europe/Madrid, PHP is handling fine the utc to timezone conversion with and without daylight savings...

**Comment by JakeOcean** [comment]
I do have auto timezone enabled, should I try and disable?

Here is a screenshot showing the columns, but keep in mind the trips above this one were before I correctly set my devices timezone.

![Screen Shot 2023-02-27 at 2 57 36 PM](https://user-images.githubusercontent.com/22035949/221669593-b2aac90d-e083-4197-99d2-5d81b5dda0db.png)

**Comment by eusonlito** [comment]
Yes, try to disable the automatic timezone inside vehicle. Anyway I testing timezone conversions using several timezones.

**Comment by eusonlito** [comment]
Update the source before try disabling the automatic timezone because there was an bug with boolean casting on vehicle.

**Comment by JakeOcean** [comment]
The times are correct now after a pull and disabling autotimezone!
