### ISSUE TITLE
Add Hebrew Translation

### ISSUE THREAD

**Issue by aamiel1** [eusonlito/GPS-Tracker#50]
Hi,

I like to add hebrew translation to the system.
Can you please advise how to do it,
including adjusting the direction from right to left of all pages. 

10x

**Comment by eusonlito** [comment]
Hi! You can create a copy of folder https://github.com/eusonlito/GPS-Tracker/tree/master/resources/lang/en with the hebrew translations and I will configure the code to allow rtl languages.

Thanks!

**Comment by aamiel1** [comment]
Hi.

When select Hebrew language please also change the date time format from "2024-04-01 15:23:29" -> "01/04/2024 15:23:29" in all plase.

Thanks,

**Comment by eusonlito** [comment]
Sorry, but the date formats are global and not related with languages.
