### ISSUE TITLE
Alarm Not Working 

### ISSUE THREAD

**Issue by imanbahmani** [eusonlito/GPS-Tracker#52]
i set alarm liked this
![Screenshot from 2024-03-31 13-22-29](https://github.com/eusonlito/GPS-Tracker/assets/5757318/55943748-f1bc-408a-9ddb-aa4ba50ee177)

and set my alarm start with 00:01 until the 23:59 

i set maximum speed area entry,exit and geofence entry and exit in my admin panel
I also connected the alarms to a vehicle which is my car And this connection is registered in the database

As you can see in the map, I entered and exited these coordinates, but no alarm was registered for me in the system!
I wanted to see what the problem is?

**Comment by imanbahmani** [comment]
![Screenshot from 2024-03-31 13-29-31](https://github.com/eusonlito/GPS-Tracker/assets/5757318/2837a8b4-276c-4f8a-93e5-19eaa778153d)

this my time

**Comment by eusonlito** [comment]
Can you test it without the dates filter? The alarm only is executed one time for each one until is closed from home or from alarm notifications panel.

**Comment by imanbahmani** [comment]
I tested the routes again without setting the clock and no alarm was registered @eusonlito 
What do you think the problem could be?

**Comment by imanbahmani** [comment]
![Screenshot from 2024-03-31 19-54-15](https://github.com/eusonlito/GPS-Tracker/assets/5757318/fa51e73d-70ec-408c-be0d-be21210f498d)

This photo shows that I have entered and exited these geographic locations, but no alarm has been registered.

**Comment by eusonlito** [comment]
Do you have related the alarms with these vehicle?

**Comment by imanbahmani** [comment]
![Screenshot from 2024-03-31 20-27-48](https://github.com/eusonlito/GPS-Tracker/assets/5757318/3ebfe9fe-d310-4e60-b0fe-38392e7b3402)


Yes

**Comment by eusonlito** [comment]
Can you screeshot the section vehicle > alarms and vehicle > notifications?

**Comment by imanbahmani** [comment]
![Screenshot from 2024-03-31 20-33-14](https://github.com/eusonlito/GPS-Tracker/assets/5757318/2639eba4-7f98-460e-bfcb-cb83b717add2)

This is translate to persian

**Comment by imanbahmani** [comment]
![Screenshot from 2024-03-31 20-38-46](https://github.com/eusonlito/GPS-Tracker/assets/5757318/831f51fb-bcc5-40a6-9aff-27bcb3f9ec39)
![Screenshot from 2024-03-31 20-38-25](https://github.com/eusonlito/GPS-Tracker/assets/5757318/0576772b-a840-49ce-85a2-9d1991a94997)
![Screenshot from 2024-03-31 20-37-27](https://github.com/eusonlito/GPS-Tracker/assets/5757318/d853ee4a-a166-4e7a-bf3d-7aa0f76b4aaf)

**Comment by eusonlito** [comment]
mmmm, ok, let me do some tests. I have also alarms and are working without problem...

**Comment by imanbahmani** [comment]
thanks

**Comment by eusonlito** [comment]
Do you have some error log in Monitor > Logs > laravel > 2024 > 03 > 31?

**Comment by imanbahmani** [comment]
on server  or artisan?

**Comment by imanbahmani** [comment]
![Uploading Screenshot from 2024-03-31 21-04-30.png…]()

**Comment by eusonlito** [comment]
If you haven't a laravel folder, then there aren't any error.

**Comment by imanbahmani** [comment]
How can I find out where the problem comes from?
Shouldn't I have entered a special order in Artisan for the alarm section?

**Comment by eusonlito** [comment]
I'm going to do some test tomorrow with my device.
