### ISSUE TITLE
Error al Iniciar Servidor

### ISSUE THREAD

**Issue by ysernah** [eusonlito/GPS-Tracker#57]
Buenas amigo me sale este error al crear un servidor quiero conectar mi celular a la aplicacion con app traccar Client y quiero crear el puerto pero me sale ese error al guardar
![image](https://github.com/eusonlito/GPS-Tracker/assets/43530180/b9f3291b-4b11-401f-8ad8-ee8b756f6c38)

**Comment by eusonlito** [comment]
Qué binario de PHP estás usando en tu servidor?

**Comment by ysernah** [comment]
Hola amigo si este es C:\wamp64\bin\php\php8.2.13

**Comment by eusonlito** [comment]
Vale, edita el fichero `.env` y añade esa ruta en:

```
PHP_BINARY=C:\wamp64\bin\php\php8.2.13
```

Después actualizas el código con:

```
./composer deploy
```

Y mira si ya puedes crear el servidor.

**Comment by ysernah** [comment]
Excelente gracias  :)
