### ISSUE TITLE
Docker Build fail

### ISSUE THREAD

**Issue by SOG-web** [eusonlito/GPS-Tracker#62]
failed to solve: process "/bin/sh -c ./composer install --no-dev --optimize-autoloader --classmap-authoritative" did not complete successfully: exit code: 1

**Comment by SOG-web** [comment]
`
﻿﻿Generating optimized autoload files
4.119 > Illuminate\Foundation\ComposerScripts::postAutoloadDump
4.134 > @php artisan package:discover --ansi
4.276 
4.281 In Connection.php line 813:
4.281                                                                                
4.281   SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for gpstracker  
4.281   -mysql failed: Name or service not known (Connection: mysql, SQL: select ta  
4.281   ble_name as `name`, (data_length + index_length) as `size`, table_comment a  
4.281   s `comment`, engine as `engine`, table_collation as `collation` from inform  
4.281   ation_schema.tables where table_schema = 'gpstracker' and table_type in ('B  
4.281   ASE TABLE', 'SYSTEM VERSIONED') order by table_name)                         
4.281                                                                                
4.281 
4.282 In Connector.php line 65:
4.282                                                                                
4.282   SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for gpstracker  
4.282   -mysql failed: Name or service not known                                     
4.282                                                                                
4.282 
4.285 In Connector.php line 65:
4.285                                                                                
4.285   PDO::__construct(): php_network_getaddresses: getaddrinfo for gpstracker-my  
4.285   sql failed: Name or service not known                                        
4.285                                                                                
4.285 
4.291 Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
------
`

**Comment by eusonlito** [comment]
I'm reviewing some issues with the netwotk configuration in the latest docker versions.

**Comment by SOG-web** [comment]
ok thanks so much, but I already got it working



I splitted the compose file into two due to network issues

**Comment by eusonlito** [comment]
Can you paste here your solution? Thanks!

**Comment by SOG-web** [comment]
Am currently in transit. I will past the solution once I settle down

**Comment by eusonlito** [comment]
I think is solved with my changes.

Regards,
Lito.
