### ISSUE TITLE
Can't Seed database

### ISSUE THREAD

**Issue by jesusv1967** [eusonlito/GPS-Tracker#64]
Hello, I have the same issue, and i'm using Windows.
Appears this error:

In Container.php line 906:
Target class [Database\Seeders\Database] does not exist.
In Container.php line 904:
Class "Database\Seeders\Database" does not exist

Thank you for your work, is great

**Comment by eusonlito** [comment]
Sorry, windows is not supported by the requirements to be able to run the protocol servers.

**Comment by jesusv1967** [comment]
thnak you, try with linux.
