### ISSUE TITLE
Adding additional data to trips

### ISSUE THREAD

**Issue by greatwitenorth** [eusonlito/GPS-Tracker#67]
I'm interested in extending GPS Tracker to allow for arbitrary meta data to be attached to a trip. We have a use case where we need to track work/personal trips. At first I thought of just extending the database, but I'm wondering if we could come up with something more flexible that would allow for arbitrary meta data on and entity.

I've worked pretty extensively in Laravel so I'd be happy to help implement this feature.

**Comment by eusonlito** [comment]
Perhaps this case could be solved by adding tags? The problem with attributes (among others) is that they complicate the interface a lot.
