### ISSUE TITLE
Installation docker build error

### ISSUE THREAD

**Issue by michalis97500** [eusonlito/GPS-Tracker#68]
Hello, I am trying to set this up to test and have run into an issue with docker build : 
![image](https://github.com/eusonlito/GPS-Tracker/assets/62388610/b932557a-9273-4ec5-908d-bc25ad976b7d)

**Comment by eusonlito** [comment]
Please, test again, you `cp` command is outdated 😅 and I have updated the build script.

**Comment by michalis97500** [comment]
I am closing the issue then! Thank you
