### ISSUE TITLE
Cannot open side menu in mobile version

### ISSUE THREAD

**Issue by chitkiu** [eusonlito/GPS-Tracker#78]
Hi, I tried to use site in mobile device, but side menu don't work at all.

https://github.com/user-attachments/assets/a0d84886-2090-4b5a-9d1a-f99e1020b5a3

https://github.com/user-attachments/assets/e605204a-b3c2-463f-94f6-ffe0d3239f29

**Comment by eusonlito** [comment]
I have tested mobile version on multiple mobile browsers without problem. What's browser are you using?

**Comment by chitkiu** [comment]
One video from safari, second - chrome
Both on iPhone with iOS 18
Now I tried from android - all good

**Comment by eusonlito** [comment]
Ok, I need to see how to debug on iOS.

Thanks!

**Comment by chitkiu** [comment]
Also I find other bug - with trip selection. I can’t select other trip from drop-down menu, but can using arrows. Also on iPhone(chrome and safari)

https://github.com/user-attachments/assets/d1df398d-7a54-4459-a75f-5f427967d093
