### ISSUE TITLE
No estoy pudiendo levantar el programa en hostinger

### ISSUE THREAD

**Issue by VilliHolz** [eusonlito/GPS-Tracker#87]

**Comment by eusonlito** [comment]
1. Tienes algún error durante la instalación o bien es durante el uso?
2. El alojamiento cumple con los requisitos de uso? https://github.com/eusonlito/GPS-Tracker/wiki/%5BES%5D-Inicio#requisitos
3. En Monitor > Requisitos dispone de todas las funciones habilitadas?
4. Has revisado los logs en Monitor > Logs > laravel?
