### ISSUE TITLE
Data cannot be parsed

### ISSUE THREAD

**Issue by teguhraharjo17** [eusonlito/GPS-Tracker#89]
![Gambar WhatsApp 2024-11-26 pukul 09 04 22_02a55762](https://github.com/user-attachments/assets/d932fac4-2017-4b8a-88b6-ca6c5c929c9b)

![Gambar WhatsApp 2024-11-22 pukul 18 58 36_5b1d84f0](https://github.com/user-attachments/assets/6d941d9f-41db-4cfd-ab64-8039e3b4320b)

why can't my FMB 140 data be parsed?

**Comment by eusonlito** [comment]
Can you send me the log?
