### ISSUE TITLE
WWW.MUNDOGPS.ORG Tu web de traccar y trackers.

### ISSUE THREAD

**Issue by mapoloco** [eusonlito/GPS-Tracker#9]
En www.mundoGPS.org ya te dijimos que no paras de espamear esta aplicación. Por Forocoches igual, y encima de ayudarte por telegram https://t.me/GPStraccar , no paras de spamear. 

QUE PESADO QUE ERES. por favor, deja de espamear.

**Comment by eusonlito** [comment]
Hola, perdona, al único que veo spameando en un proyecto open source es a ti.

Cuál es el problema de indicar que hay más plataformas que Traccar? Es tu coto privado? Está prohibido programar otras plataformas sobre una temática?

Alguien como tú que no aporta absolutamente a la comunidad open source criticando a otros que sí dedican su tiempo a los demás.

Tú, que simplemente tienes mundogps.org para ganar dinero a costa de los que simplemente necesitan algo de ayuda, ya que estás contínuamente spameando referidos en el grupo.

No voy a borrar tu mensaje, porque te retratas perfectamente como persona.

Por favor, deja de molestar a los que queremos una comunidad sana.
